### ISSUE TITLE
[Question] Refresh token logic concerns

### ISSUE THREAD

**Issue by minhnimble** [Thieurom/NimbleSurvey#23]
## Issue

Right now I notice that you apply the refresh token logic at each time the application triggers to load the survey list when calling the `surveyList` function from the API client. I am curious on why you choose to implement the refresh token logic like this approach? And how would you solve the issue when user alters the device's time to make the token check always passes but the token is actually expired (server will return 401 core here) and the user is still active on the current session?
https://github.com/Thieurom/NimbleSurvey/blob/5c4bb3a47eee9dec46e45bb3f5679a824a099c5a/NimbleSurvey/NimbleSurveyClient/NimbleSurveyClient.swift#L76-L120

At the same time, if we need to apply the token refresh logic for other endpoints later on, this approach will create duplicated token refresh logic code in every endpoint, which affects the scalability in the future. Do you have any solution for this problem?

**Comment by Thieurom** [comment]
@minhnimble
- If you look more closely, the private helper `validCredential()` does not refresh the token every time it is triggered.
https://github.com/Thieurom/NimbleSurvey/blob/1984c4de39024e63925a862750606aed5975100a/NimbleSurvey/NimbleSurveyClient/NimbleSurveyClient.swift#L98-L119

  It first checks if there's any credential being stored in the keychain. Then it checks whether it is still valid or not.
If it is still valid, it return immediately (then we can make authenticated API request like getting survey list with it). If not, we'll request a refresh credential (then store to the keychain to make other API requests).

- When user alters the device's time to make the token check always passes but the token is actually expired, the survey list request gets called. But then the server returns 401, it propagates to the network layer throwing an `APIError.network` error. Then currently `NimbleClient` throws `NimbleSurveyError.failedToGetSurveys`. We should refine other cases of `NimbleSurveyError` with the error **"The access token was revoked"**. So the view layer (HomeViewController) can catch this error and do something about it like show the message "Your session is expired", and show the Login screen. But that might be another PR.

- Since all the logic checks the existence, validity, and refreshing new credentials being encapsulated in `validCredential` method, we can easily apply for other endpoints without duplicated code. For eg:
```
func surveyDetail(id: String) -> Single<Survey> { 
         return validCredential() 
               .flatMap { [weak self] _ in 
                     guard let self = self else { 
                           return .error(NimbleSurveyError.unAuthorized) 
                     }  
  
                     return self.nimbleSurveyAPI.surveyDetail(id: id)
             } 
}
...
```

**Comment by minhnimble** [comment]
@Thieurom thank you for your well-organized answer there. Regarding your response, I would like to continue the discussion as follow:

> If you look more closely, the private helper validCredential() does not refresh the token every time it is triggered.
...(code quote)...
It first checks if there's any credential being stored in the keychain. Then it checks whether it is still valid or not.
If it is still valid, it return immediately (then we can make authenticated API request like getting survey list with it). If not, we'll request a refresh credential (then store to the keychain to make other API requests).

→ I am well aware your entire flow logic in the `validCredential()` function. `The refresh token logic` I mention here is about this entire flow you explained above, not just the part it triggers the refresh token API call in case you are a bit confused on my point. 

And again, my main concern about your validation on the credential stored in the keychain part is that you use `Date()` to check if the token is valid. It can be seen that this Date value can be modified and potentially cause the validation to not work as what you originally intend to. So, that is why I raise the question here.

> When user alters the device's time to make the token check always passes but the token is actually expired, the survey list request gets called. But then the server returns 401, it propagates to the network layer throwing an APIError.network error. Then currently NimbleClient throws NimbleSurveyError.failedToGetSurveys. We should refine other cases of NimbleSurveyError with the error "The access token was revoked". So the view layer (HomeViewController) can catch this error and do something about it like show the message "Your session is expired", and show the Login screen. But that might be another PR.

→ Thank you for the answer. I am just curious that we already have the refresh token API to help refresh the token so the end goal is to let the user continue to use the application seamlessly without any disruption. Why do you choose to the approach to show the Login screen and ask the user to authenticate again instead of refreshing the token automatically? 🤔

> Since all the logic checks the existence, validity, and refreshing new credentials being encapsulated in validCredential method, we can easily apply for other endpoints without duplicated code. 

-> So just want to clarify your point again, you are saying it is totally fine that for every new endpoint, to apply the refresh token check logic for them, we will add one line `validCredential` before calling the API and it doesn't look like duplicated code to you, is that correct?

**Comment by Thieurom** [comment]
Thank you @minhnimble for your detailing the issues of my implementation.
I revised the code regarding refreshing token logic, please have a look at #32. Any follow-up suggestions would be very appreciated.
